source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins

# Added to resolve an issue:
# https://github.com/jekyll/jekyll/issues/8523
gem "webrick"

# Add to install jekyll-archives plugin
group :jekyll_plugins do
  gem "jekyll-archives"
end
